name: learnplay
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.


dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  equatable: ^2.0.3
  email_validator: '^1.0.6'
  dio: ^4.0.6
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.15
  flutter_profile_picture: ^2.0.0
  flutter_easyloading: ^3.0.5
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.1.0
  animated_text_kit: ^4.2.2
  get: ^4.6.5
  file_picker: ^3.0.4
  http_parser: ^4.0.1
  mime_type: ^1.0.0
  asuka: ^2.0.0+1
  image_picker_windows: ^0.1.0+2
  image_picker_platform_interface: ^2.5.0
  intl: ^0.17.0
  image_picker: ^0.8.5+3
  shimmer: ^2.0.0
  jwt_decoder: ^2.0.1
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0
  badges: ^2.0.3
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  logger: ^1.1.0
  cached_network_image: ^3.2.1
  timeago: ^3.2.2
  universal_io: ^2.0.4
  permission_handler: ^10.0.0
  connectivity_plus: ^2.3.6
  
dependency_overrides:
  ffi: ">=2.0.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  msix: ^2.8.18

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/

scripts:
  # to run scripts: slidy run build-apk
  connect: adb -s RX8N8023CMT reverse tcp:3000 tcp:3000
  connect_socket: adb -s RX8N8023CMT reverse tcp:3001 tcp:3001
  
  build-apk: flutter build apk --no-sound-null-safety
  build-linux: flutter build linux --no-sound-null-safety
  build-windows: flutter build windows --no-sound-null-safety
